repos:
- repo: local
  hooks:
    - id: mise-lint
      name: mise lint
      entry: mise
      args: ["run", "lint"]
      language: system
      pass_filenames: false
- repo: https://github.com/terraform-docs/terraform-docs
  rev: v0.12.0
  hooks:
    - id: terraform-docs-go
      args: ["."]